-- CreateTable
CREATE TABLE `App` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,
    `description` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `App_name_key`(`name`),
    PRIMARY KEY (`id`)
) AUTO_INCREMENT=100001 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
